[package]
name = "router-worker"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1.77"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.40"
worker = "0.0.24"
