name = "tunnel-router"
workers_dev = true
compatibility_date = "2024-01-29"
main = "build/worker/shim.mjs"

[build]
command = "worker-build --release"

[[durable_objects.bindings]]
name = "TUNNEL"
class_name = "DurableRouter"

[[migrations]]
tag = "v1"
new_classes = ["DurableRouter"]
